export const factors = [
  { text: "T24", value: "T24" },
  { text: "P24", value: "P24" },
  { text: "T", value: "T" },
  { text: "P", value: "P" },
  { text: "ww", value: "ww" },
  { text: "N", value: "N" },
  { text: "P3", value: "P3" },
  { text: "vv", value: "vv" },
  { text: "W1", value: "W1" },
  { text: "W2", value: "W2" },
  { text: "Td", value: "Td" },
  { text: "h", value: "h" },
  { text: "Nh", value: "Nh" },
  { text: "R6", value: "R6" },
  { text: "W", value: "W" },
  { text: "ID", value: "ID" },
  { text: "等压线", value: "等压线" },
]

export const hourItems = [
  { text: "02时", value: "02" },
  { text: "05时", value: "05" },
  { text: "07时", value: "07" },
  { text: "08时", value: "08" },
  { text: "11时", value: "11" },
  { text: "14时", value: "14" },
  { text: "17时", value: "17" },
  { text: "20时", value: "20" },
  { text: "23时", value: "23" },
]
